### ISSUE TITLE
PWA app

### ISSUE THREAD

**Issue by kaldan007** [OpenPecha/pecha.org-feedbucket#101]
Description : 
Pecha.org need to integrate pwa (progressive web apps) so that user can experience the website similar to mobile app.

Implementation steps : 

- [x] create manifest.json
- [x] create service_worker.js
- [x] update html to link manifest.json and register service_worker.js
- [x] Check Manifest and Service Worker status in dev tool
- [x] Test the "Add to Home Screen" feature in mobile device

**Comment by Lungsangg** [comment]
@lobsam it is solved, can you please test in your mobile in dev.pecha.org: 
![Image](https://github.com/user-attachments/assets/4d6a1970-e79a-4c12-9b1f-ab7ea4ec6755)

**Comment by lobsam** [comment]
@Lungsangg "error: base.html could not be found"
![Image](https://github.com/user-attachments/assets/4d5181ff-0177-4091-80f3-837c7b55b2ff)

**Comment by Lungsangg** [comment]
Above bug are fixed. The pwa install button will appear for 10 second and if user does not install, then it will disappear until page get reload. 

If pwa is installed, the button wont appear again.

**Comment by lobsam** [comment]
@Lungsangg 

- Install button is disapearing after some seconds, which need to be appear for 10 - 20 seconds.
- Current install button needs to be redesign which should include:
   - Pecha Logo
   - Cross icon : if user does not want to install and avoid the install button
