### ISSUE TITLE
[CR0025] Replace default dropdown with custom dropdown

### ISSUE THREAD

**Issue by lobsam** [OpenPecha/pecha.org-feedbucket#105]
**Problem defination**:
Pecha.org is currenly using default html dropdown which does not support custom css stying like Padding and Margin etc,
Which is  required when we display tibetan text

**Implementation steps**

- [x] list all default dropdown
- [x] replace it with custom dropdown

**Comment by drupchen** [comment]
could only check in the "share menu" of existing sheets. Don't know if there are at any other locations on the website
