### ISSUE TITLE
RFC012 Add a dropdown with user Profile on signup

### ISSUE THREAD

**Issue by lobsam** [OpenPecha/pecha.org-feedbucket#106]
this RFC012 is related to [CR012](https://github.com/orgs/OpenPecha/projects/87/views/1?sliceBy%5Bvalue%5D=Iteration+4&pane=issue&itemId=79083825)

**Problem defination:**
Pecha asks new users if they are "educators". We want to know the educational background of our users instead.

implentation:

- [x] setup input field 
- [x] setup new field in database

Owner: 
@lobsam

**Comment by drupchen** [comment]
not sure this is the new dropdown menu.

Need to integrate the Tibetan localization

**Comment by drupchen** [comment]
- Tibetan locale not working
- need to check that Tibetan letters won't be cut

**Comment by lobsam** [comment]
> * Tibetan locale not working
> * need to check that Tibetan letters won't be cut

@drupchen @Lungsangg  la Tibetan locale is related to django PO file.

**Comment by Lungsangg** [comment]
@lobsam, tibetan is locale in po is updated and its working fine, can you please test in dev.pecha.org

**Comment by drupchen** [comment]
![Image](https://github.com/user-attachments/assets/fce7613e-d168-4a6c-be02-0b16071f5978)

The top is cut off
