### ISSUE TITLE
RFC028 Need to have more formatting options in texts

### ISSUE THREAD

**Issue by lobsam** [OpenPecha/pecha.org-feedbucket#152]
This RFC is related to [CR028](https://github.com/orgs/OpenPecha/projects/87/views/1?pane=issue&itemId=80878398)

### Problem defination: 
Currently, the only formatting options built-in from Sefaria are bold, italics, and similar basic formatting.

### What we need:
We will need to have access to more formatting options, like color, different typefaces etc. in order to properly present all the annotations we'll receive from the data team.

### Implementations:

- [x] Implement anotation and styling class in `Pecha_api` (ie json text)
- [x] define css property for each anotation in` Pecha.org`

**Comment by lobsam** [comment]
@drupchen as of now we only have 3 anotations and i have applied css styling properties respectively.

1. Sapche (color : "pecha theme color", Italic)
2. Quotation (Underline)
3. Citation (color : "yellow", Bold)

**Comment by drupchen** [comment]
Is this what is expected?

![Image](https://github.com/user-attachments/assets/04766553-810f-41bc-b574-fb6fcbda1237)
