### ISSUE TITLE
RFC029: update new sheet module from Sefaria

### ISSUE THREAD

**Issue by lobsam** [OpenPecha/pecha.org-feedbucket#167]
This RFC is related to [RFW029](https://github.com/orgs/OpenPecha/projects/87/views/1?sliceBy%5Bvalue%5D=Iteration+5&pane=issue&itemId=79220233)

### Problem defination: 
This RFC is for implementing sefaria's new sheet editing features to pecha.org

### Implementation:

- [x] feature out changes that need to be done on Reacjs or Django part.
- [x] cherry picking sefaria features and implement it to pecha

**Comment by drupchen** [comment]
I can't find a way to accurately reach, let's say, the 3rd segment of 2nd chapter of སྤྱོད་འཇུག་.

Also, how do I navigate in the sapche of the commentary of the ཀུན་བཟང་སྨོན་ལམ།?

If that is not possible, it's better we stay with the old editor.
