### ISSUE TITLE
ensure Trending Topics always has content

### ISSUE THREAD

**Issue by drupchen** [OpenPecha/pecha.org-feedbucket#196]
# Issue

Trending topics doesn't have any entries.

# Expected

The first 6 topics with sheets mostly consulted are always shown.

# Implementation Steps : 

- [x] Study trending topic related code
- [x] Test in dev.pecha.org

**Comment by Lungsangg** [comment]
## Trending Topic Criteria:

A topic is considered "trending" if:
a) It appears in multiple sheets
b) It has been worked on by more than one author

Ranking Mechanism:
- Sorts topics by the number of different sheet authors associated with the topic(descending order)
- More collaborative topics rise to the top
- Returns top 14 topics in trending list

Caching Mechanism:
- The cached list of trending topics remains accessible for 6 hours
- After 6 hours,  the trending topics will be recalculated

Time Frame : 
- Above criteria will be valid for sheets modified within the last 7 days (we can extend it to like 14 or 20 days)
