### ISSUE TITLE
CR012: Add a dropdown with user profiles on Sign Up

### ISSUE THREAD

**Issue by drupchen** [OpenPecha/pecha.org-feedbucket#60]
Solved by: [RFC012](https://github.com/orgs/OpenPecha/projects/87/views/1?sliceBy%5Bvalue%5D=Iteration+4&pane=issue&itemId=80171222)

## Background
Sefaria asks new users if they are "educators". We want to know the educational background of our users instead.

## input
table 3 in [Figma board](https://www.figma.com/board/3e99XOeqI7aupSZ5iWle7l/Pecha.org-Localization-Flows?node-id=0-1&t=qlwda8MazrEj1CVW-1)

![image](https://github.com/user-attachments/assets/37c10fd1-af11-41b4-ac57-edd2b700e8e3)

**Comment by kaldan007** [comment]
Add translator in the list
