### ISSUE TITLE
CR022: Tibetan webfonts not applied everywhere

### ISSUE THREAD

**Issue by drupchen** [OpenPecha/pecha.org-feedbucket#71]
## Places where webfonts are not applied:

- [x] 1. title of new sheet
![image](https://github.com/user-attachments/assets/aaa07f2c-3d77-4778-8387-0c33777528ea)

- [x] 2. sheet "Text" component
![image](https://github.com/user-attachments/assets/fb70aeca-7cd7-46a4-87f5-f304c6d2e4b9)

- [x] 3. new sheet >> add source >> browse to a segment
![image](https://github.com/user-attachments/assets/5f9e11a3-63f4-47d3-8c0a-d9cc066f53c1)

- [x] 4. path element except for the first one
![image](https://github.com/user-attachments/assets/7b0617f7-d08a-4fbf-85cb-a57fc1154113)

- [x] 4.bis preview text not in webfont
![Image](https://github.com/user-attachments/assets/eab0045a-b99b-499b-bbe6-679e886b2236)

- [x] 5. new sheet >> "Comment" component >> add to sheet
![image](https://github.com/user-attachments/assets/7d3769df-ed7c-4da6-bef3-556c91f8d9da)

- [x] 5.bis text in editor not in webfont 
![Image](https://github.com/user-attachments/assets/57ebc318-8ba8-4b8d-a1d9-7acf6a4d4bbe)

- [x] 6. open saved sheet >> click on "Share"
![image](https://github.com/user-attachments/assets/b43fe0cc-dffa-45ca-83b8-6d846bb47c41)
![image](https://github.com/user-attachments/assets/89da6122-f6d8-480b-9fca-68cff6764edc)

- [x] 6.bis The tags are not in webfont
![Image](https://github.com/user-attachments/assets/0be1ed8c-0f43-424f-86c7-80880cc598f3)

- [x] 7. open sheet in view mode 
![image](https://github.com/user-attachments/assets/5a03e1fe-01f0-4af4-80d8-4e6951f6ef7c)

- [x] 7.bis content of sheet
![Image](https://github.com/user-attachments/assets/e8d89a76-f1aa-4480-bd3c-803023699e0e)

- [x] 8. Community page
![image](https://github.com/user-attachments/assets/ffeeeaf5-e9a3-4113-846b-1ae69c7234ac)

- [x] 8.bis Tibetan titles when locale is set to English
![Image](https://github.com/user-attachments/assets/b00efe95-4765-4ea7-8039-cfb2499d4ac0)

- [x] 9. Profile >> list of sheets: search bar + title of sheets
![image](https://github.com/user-attachments/assets/bdd2afe1-4f7d-45a5-9c3a-9bff075b2b12)

- [x] 9.bis info of sheet partially not webfont
མ་སྤེལ་བ། + སྤྱི་ལོ་ etc. + ཚོད་ལྟ།
![Image](https://github.com/user-attachments/assets/d486c9a3-92a1-49a8-b432-2b9820761094)

- [x] 10. Profile >> list of collections: title of collections
![image](https://github.com/user-attachments/assets/04a30c40-7806-42dc-929c-e485f163f44b)

- [x] 11. after clicking on "Filter"
![image](https://github.com/user-attachments/assets/c6bdb6e6-b6ba-4120-91da-6ad6a171c53a)

- [x] 12. in autocompletion proposal list
![image](https://github.com/user-attachments/assets/fa7efa58-a9cb-4d95-a2cd-2c78d043d521)

- [x] 13. Bookmarks >> time strings
![image](https://github.com/user-attachments/assets/9cb71a67-d827-43da-9f1d-45128a4a9c11)

- [x] 14. Loading
![image](https://github.com/user-attachments/assets/7ab02ae8-ed1b-4670-a457-6cde82f7e509)

- [x] 15. Help Center
![image](https://github.com/user-attachments/assets/ed907455-847e-4516-a956-f0e0f5460a3e)

- [x] 15.bis (same as 9.bis)
![Image](https://github.com/user-attachments/assets/b6bc5fe5-7501-4a10-8dc2-a3f4e0391832)

- [x] 15.bisbis help center sheet search
![Image](https://github.com/user-attachments/assets/2271d6d8-0912-43ee-bf1a-8ff1fb432297)

- [x] 16. Resources >> advanced >> add translation
![image](https://github.com/user-attachments/assets/7ffc7a78-99fd-4a0e-abb7-d2a75a513acf)

- [x] 17. Consulting a text
![Image](https://github.com/user-attachments/assets/70b82245-327d-41c4-a7c2-a7e5ac3fc026)

- [x] 18. edit history of a text BO locale:
![Image](https://github.com/user-attachments/assets/b8e9cdee-b2ca-438e-a6ae-4d3142704791)

- [x] 19. edit history of a text EN locale:
![Image](https://github.com/user-attachments/assets/8046ba27-91f6-413a-a0f2-712aa2c8d60d

- [x] 20. view setting in texts
![Image](https://github.com/user-attachments/assets/3d243aed-5d94-448c-b9e5-f29b8ba07936)

**Comment by Lungsangg** [comment]
@drupchen la, i have applied webfont to all the above places (except three, which i am not able to reproduce) and also checked on pecha.org for other missing webfont and applied on them. Can you please check on dev.pecha.org

**Comment by drupchen** [comment]
2. I don't know if it would be better to close this issue and open another one for using webfont within the editor, but this is happening:

![Image](https://github.com/user-attachments/assets/989edd72-2016-4777-9c01-bab9d6ff0b71)

The following ones have been added:

- 4.bis 
- 5.bis
- 6.bis
- 7.bis
- 8.bis
- 9.bis 
New bug: ཚོད་ལྟ། appears twice. does this require a separate card?
![Image](https://github.com/user-attachments/assets/70bf83ff-5aa7-4370-b2fa-d66d2fd96349)
- 15.bis
- 17
- 18
- 19


I have undone:
- 12

It  looks like since ZH has been added, the Tibetan strings are not webfont anymore in EN locale. How come?

**Comment by drupchen** [comment]
I have added 15.bisbis. 

added 20.

**Comment by Lungsangg** [comment]
> 2. I don't know if it would be better to close this issue and open another one for using webfont within the editor, but this is happening:
> 
> ![Image](https://github.com/user-attachments/assets/989edd72-2016-4777-9c01-bab9d6ff0b71)

> @drupchen la, i am not able to reproduce this issue in editor. Can you please let me know how to find it ?
