### ISSUE TITLE
CR028: I need to have more formatting options in texts

### ISSUE THREAD

**Issue by drupchen** [OpenPecha/pecha.org-feedbucket#79]
Solved by [RFC028](https://github.com/orgs/OpenPecha/projects/87/views/1?pane=issue&itemId=80991883)

## Background
Currently, the only formatting options built-in from Sefaria are bold, italics, and similar basic formatting.

## Need
We will need to have access to more formatting options, like color, different typefaces etc. in order to properly present all the annotations we'll receive from the data team.

We will have between 7 to 10 different types of annotation coming from data team(sapche, root text citation, root text syllables, citation origin, citation body, citation end, etc.). 

We need that each of them can be formatted in any way we want: font, size, color, background color, bold, italics, etc.

## Steps
[Sefaria says](https://developers.sefaria.org/docs/text-formatting-beyond-the-segment-level): `Modern web development encourages the use of CSS for all text styling.`
We need to find a way to use CSS formatting inside texts.

**Comment by kaldan007** [comment]
traditional styling of annotations:
རྩ་བ་མཚལ་ལ་ས་བཅད་སྐེག །
ལུང་ཁུངས་གཡུ་ལ་ལུང་འདྲེན་གསེར། །
གཞན་འདོད་རམ་ལ་བརྒལ་ལན་མཐིང་། །
