### ISSUE TITLE
Bug: Community in BO locale yields error page

### ISSUE THREAD

**Issue by drupchen** [OpenPecha/pecha.org-feedbucket#94]
Reproduce:

- Go to Community page in English locale
- switch from EN to BO

Issue:

![Image](https://github.com/user-attachments/assets/721d4c09-e21c-4346-95f0-a980e65f9594)

**Comment by kaldan007** [comment]
![Image](https://github.com/user-attachments/assets/28f8e2bd-14cb-4c5e-9c3d-98dc398beb21)

It is working from my side @lobsam suspect it is due to google sheet.

**Comment by drupchen** [comment]
solved by connecting staging mongodb to the production server
